### PR TITLE
Updated Swift Package version to 5.0

### PR DESCRIPTION
**Pull request by Joebayld**
This makes the current library more current and gives support for newer versions of Xcode. This might be breaking changes though.

### CODE REVIEW

**Comment by dclelland** [comment]
Do all the source files need to be moved to a new folder? Can we just leave them in Sources? (I'm not really familiar with Swift Package Manager).

If they do, will likely need to also update the [podspec file](https://github.com/dclelland/Gong/blob/master/Gong.podspec) and run `pod install` again on the sample project.

**Comment by Joebayld** [comment]
Yeah for SPM to work it has to be in sub folder of Sources with the name of the package. 

Joe

**Comment by dclelland** [comment]
@Joebayld can you please fix this so Cocoapods also works?

**Comment by Joebayld** [comment]
I’m not too familiar with pods as I don’t use it. Is it as simple as updating the path variables in the pod file?

**Comment by dclelland** [comment]
Yeap, should be about that easy.

**Comment by Joebayld** [comment]
Fixed it - just needs to be checked / tested. Also likely needs a new tag / version number. 

Joe

**Comment by Joebayld** [comment]
@dclelland Would you like to merge / tag it?

**Comment by dclelland** [comment]
Published now; sorry for the delay!

**Pull request merged**
